goes-processor processing bulk \
  --satellite 19 \
  --product ABI-L2-LSTF \
  --year 2026 \
  --day 003 \
  --hour all \
  --minute all \
  --input-dir data/raw \
  --output-dir data/processed_01_original \
  --format both \
  --overwrite yes